### ISSUE TITLE
Unnatural sidebar transition on viewport resize

### ISSUE THREAD

**Issue by sam-hunt** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#13]
The sidebar undergoes an unnatural transition when the viewport is resized from medium to small.

Specifically, on resizing down from the medium to small bootstrap limiting resolutions, the sidebar moves from the left hand side, to the right hand side, and then immediately begins a 'hide' transition, rather than  being hidden immediately.

This is reproducible on the demo site by horizontally resizing the window down to mobile-width:
http://lbd-pro-angular2.creative-tim.com/dashboard

**Comment by alexandru-paduraru** [comment]
@sam-hunt thank you for letting us know. We will have a look and fix this in the next release. Probably the transition animation is doing that thing. We have written a patch that will move the sidebar to the left side on mobile: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/issues/20

Best,
Alex
