### ISSUE TITLE
After Updating package.json, dropdowns do not work

### ISSUE THREAD

**Issue by diegoquirino** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#31]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After upgrade package.json, app full works correctly.

# Current Behavior

After upgrade package.json, dropdowns do not work.

# Failure Information (for bugs)

(none)

## Steps to Reproduce

1. Upgrade package.json (like file attached) [_package.json.txt](https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-angular/files/3129844/_package.json.txt)
2. Upgrade angular.json (like file attached) [_angular.json.txt](https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-angular/files/3129842/_angular.json.txt)
3. Upgrade all code for sweetalert2, to call method Swap.fire() instead of swap()
4. Run npm install / ng serve
5. Open localhost:4200
6. Try to click "configuration" or any other dropdown on top right screen (they do not open)

## Context

(none)

* Device: Dell XPS 15
* Operating System: Windows 10
* Browser and Version: Chrome, v. 73.0.3683.103 (Versão oficial) 64 bits

## Failure Logs

(no logs - I'd like to have some...)

**Comment by chelaruc** [comment]
@diegoquirino Thank you for using our product. You updated from Bootstrap 3 to Bootstrap 4 and that's why the dropdowns don't work.
