### ISSUE TITLE
ERROR in : Unexpected value NouisliderModule

### ISSUE THREAD

**Issue by hpardess** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#32]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Failure Information (for bugs)
When packaging the application for production i face the error. here is the command i run:
ng build --prod --build-optimizer

## Failure Logs
`ERROR in : Unexpected value 'NouisliderModule in /light-bootstrap-dashboard-pro-angular-v1.3.0/node_modules/ng2-nouislider/src/nouislider.js' imported by the module 'Forms in /light-bootstrap-dashboard-pro-angular-v1.3.0/src/app/forms/forms.module.ts'. Please add a @NgModule annotation.`

**Comment by chelaruc** [comment]
Hi, @hpardess. Thank you for using our product. Have you updated the dependences?

**Comment by hpardess** [comment]
@chelaruc : I have downloaded v1.3 and here are the relevant dependencies:
"nouislider": "9.2.0"
"ng2-nouislider": "1.7.12"

The update of dependencies have to be done by team because sometimes the upgrade of dependencies break some pieces of code.

**Comment by hpardess** [comment]
It is fixed with following changes,
"ng2-nouislider": "1.7.12" => "ng2-nouislider": "1.8.2"
import { NouisliderModule } from 'ng2-nouislider/src/nouislider'; => import { NouisliderModule } from 'ng2-nouislider';
