### ISSUE TITLE
[Feature Request] Make perfectScrollbar visible

### ISSUE THREAD

**Issue by Saifer707** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#33]
### What is your enhancement?
Hi, is it possible make perfectScrollbar always visible?

I try to set opacity to 0.6 in .ps-container .ps-scrollbar-y-rail css code but there's no effect.

Thank you!

**Comment by chelaruc** [comment]
Hi, @Saifer707. Thank you for using our product. Where have you added the css code?

**Comment by Saifer707** [comment]
Hi, @chelaruc! Thanks for the reply! I put the css code in documentation/css/documentation.css, but I tried also to put it into index.html by using <style></style> tags and it's not working anyway.

**Comment by Saifer707** [comment]
@chelaruc can you help me?

**Comment by chelaruc** [comment]
Hi, @Saifer707. Sorry for the late response. Can you add the css code in `src/assets/css/demo.css`?

**Comment by Saifer707** [comment]
Hello @chelaruc, don't worry, you're very kind!

I've tried your solution but it doesn't work. Any other suggestions?

**Comment by chelaruc** [comment]
Import this css code into one file from the sass folder:
```
.ps-container > .ps-scrollbar-x-rail,
   .ps-container > .ps-scrollbar-y-rail {
     display: block;
     min-height: 200px;
     opacity: 0.6;
   }
```
