### ISSUE TITLE
Get 50% Discount Coupon Raise 500 error 

### ISSUE THREAD

**Issue by KimSoungRyoul** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#34]
https://www.creative-tim.com/user/credit-history 

Get 50% Discount Coupon does not work 

it raise status 500 error 

please fix it

**Comment by dragosct10** [comment]
Hi, @KimSoungRyoul! Thank you for using our products. Please try again now. It was fixed. 

Regards,
Dragos

**Comment by KimSoungRyoul** [comment]
Thank you for your quick feedback
