### ISSUE TITLE
[Bug] Error When Install and Try Build

### ISSUE THREAD

**Issue by danilolopesabreu** [creativetimofficial/ct-light-bootstrap-dashboard-pro-angular#41]
### Version
v1.5.0
### Reproduction link
https://github.com/danilolopesabreu/light-bootstrap-dashboard-pro-angular-v1.5.0
### Operating System
Windows 10
### Device
ASUS ROG Core i7
### Browser & Version
Latest Ms. Edge
### Steps to reproduce
1 - Download the Light Bootstrap Dashboard Pro Angular zip file from creative-tim website.
2 - Unzip and execute:
   2.1 - npm install -g @angular/cli
   2.2 - npm install

There are 2 situations:

1 - installation error : 
C:\w\creative-tim\light-bootstrap-dashboard-pro-angular-v1.5.0>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: light-booststrap-dashboard-pro-angular@1.5.0
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"0.11.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.4
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"11.0.4" from the root project
npm ERR!   peer @angular/core@"11.0.4" from @angular/animations@11.0.4
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"11.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

After, try to run the command: npm install --legacy-peer-deps
Node modules will be installed.

2 - Build Error
So you can try: ng serve , but the error appear:
    Error: node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:18:21 - error TS2694: Namespace '"C:/w/creative-tim/light-bootstrap-dashboard-pro-angular-v1.5.0/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    18     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownButton, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:19:21 - error TS2694: Namespace '"C:/w/creative-tim/light-bootstrap-dashboard-pro-angular-v1.5.0/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

### What is expected?
install and build the app.
### What is actually happening?
error when install and build.

---
### Solution

### Additional comments
I try build and run on vercel, but same situation appear:

Error: node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:18:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
18     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownButton, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/button/ng2-dropdown-button.d.ts:19:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
19     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2DropdownButton, "ng2-dropdown-button", never, { "showCaret": "showCaret"; }, { "onMenuToggled": "onMenuToggled"; }, never, ["*"]>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/dropdown/ng2-dropdown.d.ts:38:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
38     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2Dropdown, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/dropdown/ng2-dropdown.d.ts:39:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
39     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2Dropdown, "ng2-dropdown", never, { "dynamicUpdate": "dynamicUpdate"; }, { "onItemClicked": "onItemClicked"; "onItemSelected": "onItemSelected"; "onShow": "onShow"; "onHide": "onHide"; }, ["button", "menu"], ["ng2-dropdown-button", "ng2-dropdown-menu"]>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:38:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
38     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2MenuItem, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:39:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
39     static ɵcmp: i0.ɵɵComponentDeclaration<Ng2MenuItem, "ng2-menu-item", never, { "preventClose": "preventClose"; "value": "value"; }, {}, never, ["*"]>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:74:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
74     static ɵfac: i0.ɵɵFactoryDeclaration<Ng2DropdownMenu, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:75:21 - error TS2694: Namespace '"/vercel/path0/node_modules/@angular/core/core"' has no exported member 
<!-- generated by creative-tim-issues. DO NOT REMOVE -->

**Comment by danilolopesabreu** [comment]
node -v
v16.13.0

npm -v
8.1.4

**Comment by rarestoma** [comment]
Hi @danilolopesabreu,

Thank you for working with our products.

Can you please try again with node `v14.16.1` and npm `v6.14.12`?

Thank you,
Rares

**Comment by danilolopesabreu** [comment]
Hi @rarestoma 
Thanks for the reply!
I've tried to make like you said, the install error is gone, but, the compilation error with ng2-dropdown still the same.
I instaled the NVM to manage versions of NodeJs, so i tried to execute the installation tutorial with 14.16.1 and 12.22.8 versions but the same error persist.
![ErrorNg2DropDown](https://user-images.githubusercontent.com/19998989/146763849-1e0709b3-133e-4501-a61a-de941a9bd605.jpg)

**Comment by danilolopesabreu** [comment]
i did cache clean --force to.

**Comment by danilolopesabreu** [comment]
This guy help-me, but im still don't understand why this happening.

https://github.com/angular/angular/issues/44366#issuecomment-992107509
